export const LOGIN_USER = "LOGIN_USER";
export const GET_LIST_HISTORY = "GET_LIST_HISTORY";
//admin
export const GET_LIST_ACCOUNT = "GET_LIST_ACCOUNT";
export const GET_LIST_CUSTOMER = "GET_LIST_CUSTOMER";
export const GET_LIST_PERSONAL_APPRAISAL = "GET_LIST_PERSONAL_APPRAISAL";
export const GET_LIST_BROKER = "GET_LIST_BROKER";
export const GET_LIST_CUSTOMER_TYPE = "GET_LIST_CUSTOMER_TYPE";
export const GET_LIST_VOCATIVE = "GET_LIST_VOCATIVE";
export const GET_LIST_EMPLOYEE_POSITIONS = "GET_LIST_EMPLOYEE_POSITIONS";
export const GET_LIST_EMPLOYEE = "GET_LIST_EMPLOYEE";

export const GET_LIST_BRIEF = "GET_LIST_BRIEF";
export const GET_LIST_BRIEF_SUPER_DETAIL = "GET_LIST_BRIEF_SUPER_DETAIL";
export const GET_LIST_BRIEF_POINT = "GET_LIST_BRIEF_POINT";

export const GET_LIST_ASSET = "GET_LIST_ASSET";
export const GET_LIST_FILES = "GET_LIST_FILES";
export const GET_LIST_ASSET_TYPE = "GET_LIST_ASSET_TYPE";

export const GET_LIST_APPRAISAL_PLAN = "GET_LIST_APPRAISAL_PLAN";
export const GET_LIST_APPRAISAL_PLAN_DETAIL = "GET_LIST_APPRAISAL_PLAN_DETAIL";
export const GET_LIST_APPRAISAL_DOCUMENT_DETAIL = "GET_LIST_APPRAISAL_DOCUMENT_DETAIL";
export const GET_LIST_APPRAISAL_PLAN_TYPE = "GET_LIST_APPRAISAL_PLAN_TYPE";

export const GET_LIST_PRIORITY_LEVEL = "GET_LIST_PRIORITY_LEVEL";